engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  coffeelint:
    enabled: true
    config: coffeelint.json

ratings:
  paths:
    - "**.rb"
    - "**.coffee"

exclude_paths:
  - node_modules/**/*
  - spec/**/*
