engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  coffeelint:
    enabled: true
    config: coffeelint.json
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
    - "**.coffee"

exclude_paths:
  - node_modules/**/*
  - spec/**/*
