version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2'
    volumes:
      - 'redis:/var/lib/redis/data'
  web:
    image: 'gkopylov/kanban_on_rails:1'
    build: .
    command: passenger start
    depends_on:
      - 'postgres'
      - 'redis'
    ports:
      - '3000:3000'
    volumes:
      - '.:/kanban_on_rails'
  sidekiq:
    image: 'gkopylov/kanban_on_rails:1'
    build: .
    command: sidekiq
    depends_on:
      - 'postgres'
      - 'redis'
    volumes:
      - '.:/kanban_on_rails'
volumes:
  postgres:
  redis:
